/* 
 * Material destinado ao projeto da disciplina
 * de Programação Orientada a Objetos do 
 * Bacharelado em Ciência da Computação 
 * do IFNMG - Câmpus Montes Claros
 */
package br.edu.ifnmg.poo.cinema.gui;

/**
 *
 * @author annaj
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        this.setExtendedState(MAXIMIZED_BOTH); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionarios = new javax.swing.JMenu();
        menuFuncionariosCadastrar = new javax.swing.JMenuItem();
        menuExcluirFuncionario = new javax.swing.JMenuItem();
        menuListarFuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuFilme = new javax.swing.JMenu();
        menuCadastrarFilme = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuSessao = new javax.swing.JMenu();
        menuCadasrarSessao = new javax.swing.JMenuItem();
        menuListarExcluirSessao = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuCadastrarIngresso = new javax.swing.JMenuItem();
        menuVenderIngresso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFuncionarios.setText("Funcionarios");
        menuFuncionarios.setEnabled(false);

        menuFuncionariosCadastrar.setText("Cadastrar");
        menuFuncionariosCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionariosCadastrarActionPerformed(evt);
            }
        });
        menuFuncionarios.add(menuFuncionariosCadastrar);

        menuExcluirFuncionario.setText("Excluir ou Listar");
        menuExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionarios.add(menuExcluirFuncionario);

        menuListarFuncionario.setText("Alterar");
        menuListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarFuncionarioActionPerformed(evt);
            }
        });
        menuFuncionarios.add(menuListarFuncionario);

        jMenuBar1.add(menuFuncionarios);

        jMenu2.setText("Cliente");

        menuCadastrarCliente.setText("Cadastrar");
        menuCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadastrarCliente);

        jMenuItem1.setText("Atualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        menuFilme.setText("Filme");

        menuCadastrarFilme.setText("Cadastrar");
        menuCadastrarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarFilmeActionPerformed(evt);
            }
        });
        menuFilme.add(menuCadastrarFilme);

        jMenuItem2.setText("Listar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuFilme.add(jMenuItem2);

        jMenuBar1.add(menuFilme);

        menuSessao.setText("Sessão");

        menuCadasrarSessao.setText("Cadasrar");
        menuCadasrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadasrarSessaoActionPerformed(evt);
            }
        });
        menuSessao.add(menuCadasrarSessao);

        menuListarExcluirSessao.setText("Listar e Excluir");
        menuListarExcluirSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarExcluirSessaoActionPerformed(evt);
            }
        });
        menuSessao.add(menuListarExcluirSessao);

        jMenuBar1.add(menuSessao);

        jMenu1.setText("Ingresso");

        menuCadastrarIngresso.setText("Cadastrar");
        menuCadastrarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarIngressoActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarIngresso);

        menuVenderIngresso.setText("Vender");
        menuVenderIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVenderIngressoActionPerformed(evt);
            }
        });
        jMenu1.add(menuVenderIngresso);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        setBounds(0, 0, 539, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void menuFuncionariosCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionariosCadastrarActionPerformed
        // TODO add your handling code here:
        TelaCadastrarFuncionario cadastrar = new TelaCadastrarFuncionario();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_menuFuncionariosCadastrarActionPerformed

    private void menuExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaExcluirFuncionario excluir = new TelaExcluirFuncionario();
        excluir.setVisible(true);
    }//GEN-LAST:event_menuExcluirFuncionarioActionPerformed

    private void menuListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaAlterarFuncionario alterar = new TelaAlterarFuncionario();
        alterar.setVisible(true);
    }//GEN-LAST:event_menuListarFuncionarioActionPerformed

    private void menuCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastrarCliente cadastrar = new TelaCadastrarCliente();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_menuCadastrarClienteActionPerformed

    private void menuCadastrarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarFilmeActionPerformed
        // TODO add your handling code here:
        TelaCadastrarFilme cadastrar = new TelaCadastrarFilme();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_menuCadastrarFilmeActionPerformed

    private void menuCadasrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadasrarSessaoActionPerformed
        // TODO add your handling code here:
        TelaCadastrarSessao cadastrar = new TelaCadastrarSessao();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_menuCadasrarSessaoActionPerformed

    private void menuCadastrarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarIngressoActionPerformed
        // TODO add your handling code here:
        TelaCadastrarIngresso cadastrar = new TelaCadastrarIngresso();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_menuCadastrarIngressoActionPerformed

    private void menuVenderIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVenderIngressoActionPerformed
        // TODO add your handling code here:
        TelaVenderIngresso vender = new TelaVenderIngresso();
        vender.setVisible(true);
    }//GEN-LAST:event_menuVenderIngressoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaAtualizarCliente atualizar = new TelaAtualizarCliente();
        atualizar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaListarFilme listar = new TelaListarFilme();
        listar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuListarExcluirSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarExcluirSessaoActionPerformed
        // TODO add your handling code here:
        TelaListarExcluirSessao listar = new TelaListarExcluirSessao();
        listar.setVisible(true);
    }//GEN-LAST:event_menuListarExcluirSessaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuCadasrarSessao;
    private javax.swing.JMenuItem menuCadastrarCliente;
    private javax.swing.JMenuItem menuCadastrarFilme;
    private javax.swing.JMenuItem menuCadastrarIngresso;
    private javax.swing.JMenuItem menuExcluirFuncionario;
    private javax.swing.JMenu menuFilme;
    public static javax.swing.JMenu menuFuncionarios;
    private javax.swing.JMenuItem menuFuncionariosCadastrar;
    private javax.swing.JMenuItem menuListarExcluirSessao;
    private javax.swing.JMenuItem menuListarFuncionario;
    private javax.swing.JMenu menuSessao;
    private javax.swing.JMenuItem menuVenderIngresso;
    // End of variables declaration//GEN-END:variables
}
